<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;


class Permission extends \Spatie\Permission\Models\Permission
{
    use HasFactory;

    const
        SHOW_CONTRACTS_PERMISSION = 'show_contracts_permission',
        SHOW_CONTRACT_PERMISSION = 'show_contract_permission',
        CREATE_CONTRACT_PERMISSION = 'create_contract_permission',
        UPDATE_CONTRACT_PERMISSION = 'update_contract_permission',
        DELETE_CONTRACT_PERMISSION = 'delete_contract_permission',
        CHANGE_STATUS_CONTRACT_PERMISSION = 'change_status_contract_permission',
        UPDATEABLE_CONTRACT_PERMISSION = 'updateable_contract_permission',
        CHANGE_CONTRACT_PERMISSION = 'change_contract_permission',
        SHOW_CONTRACT_PROBLEM_REASONS_PERMISSION = 'show_contract_problem_reasons_permission',
        SHOW_CONTRACT_PROBLEM_REASON_PERMISSION = 'show_contract_problem_reason_permission',
        CREATE_CONTRACT_PROBLEM_REASON_PERMISSION = 'create_contract_problem_reason_permission',
        UPDATE_CONTRACT_PROBLEM_REASON_PERMISSION = 'update_contract_problem_reason_permission',
        DELETE_CONTRACT_PROBLEM_REASON_PERMISSION = 'delete_contract_problem_reason_permission',
        SHOW_CONTRACT_QUESTIONS_PERMISSION = 'show_contract_questions_permission',
        SHOW_CONTRACT_QUESTION_PERMISSION = 'show_contract_question_permission',
        CREATE_CONTRACT_QUESTION_PERMISSION = 'create_contract_question_permission',
        UPDATE_CONTRACT_QUESTION_PERMISSION = 'update_contract_question_permission',
        DELETE_CONTRACT_QUESTION_PERMISSION = 'delete_contract_question_permission',
        SHOW_ARTICLES_PERMISSION = 'show_articles_permission',
        SHOW_ARTICLE_PERMISSION = 'show_article_permission',
        CREATE_ARTICLE_PERMISSION = 'create_article_permission',
        UPDATE_ARTICLE_PERMISSION = 'update_article_permission',
        DELETE_ARTICLE_PERMISSION = 'delete_article_permission',
        SHOW_CATEGORIES_PERMISSION = 'show_categories_permission',
        SHOW_CATEGORY_PERMISSION = 'show_category_permission',
        CREATE_CATEGORY_PERMISSION = 'create_category_permission',
        UPDATE_CATEGORY_PERMISSION = 'update_category_permission',
        DELETE_CATEGORY_PERMISSION = 'delete_category_permission',
        SHOW_PAYMENTS_PERMISSION = 'show_payments_permission',
        SHOW_PAYMENT_PERMISSION = 'show_payment_permission',
        CREATE_PAYMENT_PERMISSION = 'create_payment_permission',
        UPDATE_PAYMENT_PERMISSION = 'update_payment_permission',
        DELETE_PAYMENT_PERMISSION = 'delete_payment_permission',
        SHOW_QUESTIONS_PERMISSION = 'show_questions_permission',
        SHOW_QUESTION_PERMISSION = 'show_question_permission',
        CREATE_QUESTION_PERMISSION = 'create_question_permission',
        UPDATE_QUESTION_PERMISSION = 'update_question_permission',
        DELETE_QUESTION_PERMISSION = 'delete_question_permission',
        SHOW_ROLES_PERMISSION = 'show_roles_permission',
        SHOW_ROLE_PERMISSION = 'show_role_permission',
        CREATE_ROLE_PERMISSION = 'create_role_permission',
        UPDATE_ROLE_PERMISSION = 'update_role_permission',
        DELETE_ROLE_PERMISSION = 'delete_role_permission',
        ASSIGN_ROLE_PERMISSION = 'assign_role_permission',
        REVOKE_ROLE_PERMISSION = 'revoke_role_permission',
        GIVE_PERMISSION_PERMISSION = 'give_permission_permission',
        REVOKE_PERMISSION_PERMISSION = 'revoke_permission_permission',
        SHOW_TICKETS_PERMISSION = 'show_tickets_permission',
        SHOW_TICKET_PERMISSION = 'show_ticket_permission',
        CREATE_TICKET_PERMISSION = 'create_ticket_permission',
        ANSWER_TICKET_PERMISSION = 'answer_ticket_permission',
        UPDATE_TICKET_PERMISSION = 'update_ticket_permission',
        DELETE_TICKET_PERMISSION = 'delete_ticket_permission',
        SHOW_USERS_PERMISSION = 'show_users_permission',
        SHOW_USER_PERMISSION = 'show_user_permission',
        CREATE_USER_PERMISSION = 'create_user_permission',
        UPDATE_USER_PERMISSION = 'update_user_permission',
        DETAIL_USER_PERMISSION = 'detail_user_permission',
        ADMINS_USER_PERMISSION = 'admins_user_permission',
        DELETE_USER_PERMISSION = 'delete_user_permission',
        SHOW_FILES_PERMISSION = 'show_files_permission',
        SHOW_TRANSACTIONS_PERMISSION = 'show_transactions_permission',
        SHOW_TRANSACTION_PERMISSION = 'show_transaction_permission',
        CREATE_TRANSACTION_PERMISSION = 'create_transaction_permission',
        DELETE_TRANSACTION_PERMISSION = 'delete_transaction_permission',
        UPDATE_TRANSACTION_PERMISSION = 'update_transaction_permission',
        SHOW_SETTLEMENTS_PERMISSION = 'show_settlements_permission',
        SHOW_SETTLEMENT_PERMISSION = 'show_settlement_permission',
        SETTLE_SETTLEMENT_PERMISSION = 'settle_settlement_permission',
        REJECT_SETTLEMENT_PERMISSION = 'reject_settlement_permission',
        UPDATE_SETTLEMENT_PERMISSION = 'update_settlement_permission';


    public static array $permissions = [
        self::SHOW_CONTRACTS_PERMISSION,
        self::SHOW_CONTRACT_PERMISSION,
        self::CREATE_CONTRACT_PERMISSION,
        self::UPDATE_CONTRACT_PERMISSION,
        self::DELETE_CONTRACT_PERMISSION,
        self::UPDATEABLE_CONTRACT_PERMISSION,
        self::CHANGE_CONTRACT_PERMISSION,
        self::SHOW_CONTRACT_PROBLEM_REASONS_PERMISSION,
        self::SHOW_CONTRACT_PROBLEM_REASON_PERMISSION,
        self::CREATE_CONTRACT_PROBLEM_REASON_PERMISSION,
        self::UPDATE_CONTRACT_PROBLEM_REASON_PERMISSION,
        self::DELETE_CONTRACT_PROBLEM_REASON_PERMISSION,
        self::SHOW_CONTRACT_QUESTIONS_PERMISSION,
        self::SHOW_CONTRACT_QUESTION_PERMISSION,
        self::CREATE_CONTRACT_QUESTION_PERMISSION,
        self::UPDATE_CONTRACT_QUESTION_PERMISSION,
        self::DELETE_CONTRACT_QUESTION_PERMISSION,
        self::CHANGE_STATUS_CONTRACT_PERMISSION,
        self::SHOW_ARTICLES_PERMISSION,
        self::SHOW_ARTICLE_PERMISSION,
        self::CREATE_ARTICLE_PERMISSION,
        self::UPDATE_ARTICLE_PERMISSION,
        self::DELETE_ARTICLE_PERMISSION,
        self::SHOW_CATEGORIES_PERMISSION,
        self::SHOW_CATEGORY_PERMISSION,
        self::CREATE_CATEGORY_PERMISSION,
        self::UPDATE_CATEGORY_PERMISSION,
        self::DELETE_CATEGORY_PERMISSION,
        self::SHOW_PAYMENTS_PERMISSION,
        self::SHOW_PAYMENT_PERMISSION,
        self::CREATE_PAYMENT_PERMISSION,
        self::UPDATE_PAYMENT_PERMISSION,
        self::DELETE_PAYMENT_PERMISSION,
        self::SHOW_QUESTIONS_PERMISSION,
        self::SHOW_QUESTION_PERMISSION,
        self::CREATE_QUESTION_PERMISSION,
        self::UPDATE_QUESTION_PERMISSION,
        self::DELETE_QUESTION_PERMISSION,
        self::SHOW_ROLES_PERMISSION,
        self::SHOW_ROLE_PERMISSION,
        self::CREATE_ROLE_PERMISSION,
        self::UPDATE_ROLE_PERMISSION,
        self::DELETE_ROLE_PERMISSION,
        self::ASSIGN_ROLE_PERMISSION,
        self::REVOKE_ROLE_PERMISSION,
        self::GIVE_PERMISSION_PERMISSION,
        self::REVOKE_PERMISSION_PERMISSION,
        self::SHOW_TICKETS_PERMISSION,
        self::SHOW_TICKET_PERMISSION,
        self::CREATE_TICKET_PERMISSION,
        self::ANSWER_TICKET_PERMISSION,
        self::UPDATE_TICKET_PERMISSION,
        self::DELETE_TICKET_PERMISSION,
        self::SHOW_USERS_PERMISSION,
        self::SHOW_USER_PERMISSION,
        self::CREATE_USER_PERMISSION,
        self::UPDATE_USER_PERMISSION,
        self::DETAIL_USER_PERMISSION,
        self::ADMINS_USER_PERMISSION,
        self::DELETE_USER_PERMISSION,
        self::SHOW_FILES_PERMISSION,
        self::SHOW_TRANSACTIONS_PERMISSION,
        self::SHOW_TRANSACTION_PERMISSION,
        self::CREATE_TRANSACTION_PERMISSION,
        self::UPDATE_TRANSACTION_PERMISSION,
        self::DELETE_TRANSACTION_PERMISSION,
        self::SHOW_SETTLEMENTS_PERMISSION,
        self::SHOW_SETTLEMENT_PERMISSION,
        self::SETTLE_SETTLEMENT_PERMISSION,
        self::REJECT_SETTLEMENT_PERMISSION,
        self::UPDATE_SETTLEMENT_PERMISSION,
    ];


}
